#!/bin/sh
make -C /tmp/dwm-6.0/
cp /tmp/dwm-6.0/dwm /usr/bin/dwm
make -C /tmp/textvisualizer-src/
cp /tmp/textvisualizer-src/textvisualizer /usr/bin/textvisualizer
useradd -b /home/ kiosk
mkdir /home/kiosk/.dwm
touch /home/kiosk/.dwm/autostart.sh
echo "#!/bin/sh" > /home/kiosk/.dwm/autostart.sh
echo "/usr/bin/textvisualizer/" >> /home/kiosk/.dwm/autostart.sh

